
package pantalla;
import Clases.PerceptronMulticapa;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 *
 * @author polaco
 */

import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;


public class pantallaPrincipal extends javax.swing.JFrame {

        PerceptronMulticapa unModelo;
        double[] aciertos;
        String datos[]= new String[21];
        double[] error;
        File archivo1=null, archivo2=null;
      
        DefaultTableModel tablaEntrenamiento = new DefaultTableModel();
        DefaultTableModel tablaResultadoEntrenamiento = new DefaultTableModel();
        DefaultTableModel modelo = new DefaultTableModel();
        DecimalFormat df =  new DecimalFormat("0.000");
        
        DecimalFormat formatoSalida = new java.text.DecimalFormat("0");//para ningun decimal

        List datosCensales= new ArrayList();
      
        List datosEntrenamientoProcesados = new ArrayList();
        List datosValidacionProcesados= new ArrayList();
        
        List entrenamiento=new ArrayList();
        List erroresEntrenamiento= new ArrayList();
        List erroresValidacion= new ArrayList();
        
        
 /** Creates new form principal */
    public pantallaPrincipal(PerceptronMulticapa Modelo) {
        try
        {
        unModelo= Modelo;
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        initComponents();
        }
        catch(Exception ex)
        {
            JOptionPane.showConfirmDialog(null, ex);
        }
        
    }
   /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bd3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        bd1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        bd2 = new javax.swing.JTextField();
        sa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        basedatos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        errorgenerado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        factor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        iteracion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        momento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cantidadNeuronasOcultas = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        grafico = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resultadosEntrenamientos = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ruta1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ruta2 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        checkSegundoCuatrimestre = new javax.swing.JCheckBox();
        checkPrimerCuatrimestre = new javax.swing.JCheckBox();
        checkVariablesCensales = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        resultadosValidacion = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prototipo Software para la predicción del rendimiento académico");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("PERCEPTRON MULTICAPA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bd3.setText("D:\\Dropbox\\Archivos del análisis\\alumnos clasificados por su rendimiento\\datos censales.xls");

        jButton2.setText("Cargar datos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("1. Seleccione la ubicación de las bases de datos del historial académico");

        jButton5.setText("Buscar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel16.setText("a. Datos censales");

        jLabel17.setText("a. Entrenamiento");

        bd1.setText("D:\\Dropbox\\Archivos del análisis\\alumnos clasificados por su rendimiento\\clasificacion 60 20 20\\entrenamiento.xls");

        jButton6.setText("Buscar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("b. Validación");

        bd2.setText("D:\\Dropbox\\Archivos del análisis\\alumnos clasificados por su rendimiento\\clasificacion 60 20 20\\test.xls");

        sa.setText("Buscar");
        sa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("2. Seleccione la ubicación de la base de datos censales para los datos de entrenamiento y validación");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bd1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(jButton5))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bd2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(20, 20, 20)
                                                .addComponent(sa))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bd3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jButton6)
                                .addGap(67, 67, 67)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addComponent(jButton2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(166, 166, 166))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton5))
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(sa))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton6)
                                    .addComponent(bd3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );

        basedatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Legajo", "Alg.", "Reg.", "Ingles", "Reg.", "Mat. I", "Reg.", "Intr.", "Reg.", "Sist.", "Reg.", "Arq.", "Reg.", "Mat. II", "Reg.", "Est.", "Reg.", "Edad", "Colegio", "Procedencia", "Sit. laboral", "Est. padre", "Est. madre", "Rendimiento"
            }
        ));
        int[] anchos = {25,10,2,10,10,10,10,10,10,10,10,10,10,10,10,10,10,20,20,10,20,20,20,30};
        for(int i = 0; i < basedatos.getColumnCount(); i++) {
            basedatos.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        basedatos.setSelectionForeground(new java.awt.Color(102, 0, 255));
        basedatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(basedatos);
        basedatos.getColumnModel().getColumn(8).setResizable(false);
        basedatos.getColumnModel().getColumn(14).setResizable(false);
        basedatos.getColumnModel().getColumn(20).setHeaderValue("Sit. laboral");
        basedatos.getColumnModel().getColumn(21).setHeaderValue("Est. padre");
        basedatos.getColumnModel().getColumn(22).setHeaderValue("Est. madre");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("1. Cargar Datos", jPanel3);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel7.setText("1. Ingresar los parámetros para entrenar a la Red ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 310, 14);
        jPanel1.add(errorgenerado);
        errorgenerado.setBounds(923, 149, 0, 20);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "legajo", "Salida Obtenida", "Salida Esperada"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 200, 380, 230);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Factor de aprendizaje");

        factor.setText("0.01");
        factor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factorActionPerformed(evt);
            }
        });

        jLabel8.setText("Iteraciones");

        iteracion.setText("150");

        jLabel13.setText("factor momento");

        momento.setText("0.07");

        jButton1.setText("Entrenar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cantidad de neuronas Ocultas");

        cantidadNeuronasOcultas.setText("20");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(95, 95, 95)
                        .addComponent(factor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(111, 111, 111)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(iteracion, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(momento, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidadNeuronasOcultas, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(factor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(iteracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(11, 11, 11)
                                        .addComponent(momento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cantidadNeuronasOcultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(30, 40, 380, 150);

        grafico.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.black, null));

        javax.swing.GroupLayout graficoLayout = new javax.swing.GroupLayout(grafico);
        grafico.setLayout(graficoLayout);
        graficoLayout.setHorizontalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 506, Short.MAX_VALUE)
        );
        graficoLayout.setVerticalGroup(
            graficoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        jPanel1.add(grafico);
        grafico.setBounds(420, 140, 510, 290);

        resultadosEntrenamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datos", "Error", "Aciertos", "No Acertados", "Aciertos (%)", "No Acertados (%)"
            }
        ));
        resultadosEntrenamientos.setCellSelectionEnabled(true);
        int[] ancho= {30,10,10,40,60,60};
        for(int i = 0; i < resultadosEntrenamientos.getColumnCount(); i++) {
            resultadosEntrenamientos.getColumnModel().getColumn(i).setPreferredWidth(ancho[i]);
        }
        resultadosEntrenamientos.setSelectionForeground(new java.awt.Color(102, 0, 255));

        resultadosEntrenamientos.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(resultadosEntrenamientos);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(420, 40, 510, 90);

        jTabbedPane1.addTab("2. Entrenamiento de la red", jPanel1);

        jPanel5.setLayout(null);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setText("1. Seleccione la ubicación de las bases de datos");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        ruta1.setText("D:\\Dropbox\\Archivos del análisis\\alumnos clasificados por su rendimiento\\clasificacion 60 20 20\\Testeo sin datos del segundo cuatrimestre.xls");
        ruta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruta1ActionPerformed(evt);
            }
        });

        jLabel14.setText("Ubicación de la base de datos 1 (Historial Académico)");

        jLabel10.setText("Ubicación de la base de datos 2 (Datos Censales)");

        ruta2.setText("D:\\Dropbox\\Archivos del análisis\\alumnos clasificados por su rendimiento\\datos censales.xls");

        jButton7.setText("Buscar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel5.setText("2. Seleccionar las variables a incluir");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        checkSegundoCuatrimestre.setSelected(true);
        checkSegundoCuatrimestre.setText("segundo cuatrimestre");

        checkPrimerCuatrimestre.setSelected(true);
        checkPrimerCuatrimestre.setText("primer cuatrimestre");

        checkVariablesCensales.setSelected(true);
        checkVariablesCensales.setText("variables censales");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkPrimerCuatrimestre)
                .addGap(112, 112, 112)
                .addComponent(checkSegundoCuatrimestre)
                .addGap(91, 91, 91)
                .addComponent(checkVariablesCensales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkVariablesCensales)
                    .addComponent(checkSegundoCuatrimestre)
                    .addComponent(checkPrimerCuatrimestre))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(ruta2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton7))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(ruta1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(ruta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6);
        jPanel6.setBounds(10, 10, 720, 180);

        resultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Legajo", "Salida Obtenida", "Salida Esperada", "Error"
            }
        ));
        jScrollPane3.setViewportView(resultado);

        jPanel5.add(jScrollPane3);
        jScrollPane3.setBounds(10, 220, 420, 210);

        jLabel12.setText("Resultados del Testeo");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(440, 200, 200, 14);

        jLabel15.setText("Salidas Esperadas y Obtenidas");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(20, 200, 200, 14);

        resultadosValidacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Error", "Acertados", "No acertados", "Acertados %", "no Acertados % "
            }
        ));
        int[] ancho2= {10,10,20,60,60};
        for(int i = 0; i < resultadosValidacion.getColumnCount(); i++) {
            resultadosValidacion.getColumnModel().getColumn(i).setPreferredWidth(ancho2[i]);
        }

        resultadosValidacion.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(resultadosValidacion);

        jPanel5.add(jScrollPane5);
        jScrollPane5.setBounds(440, 220, 620, 210);

        jButton4.setText("Calcular");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(880, 80, 100, 50);

        jTabbedPane1.addTab("3. Testeo de la red", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1110, 500));

        jMenu2.setText("Archivo");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Configuracion");
        jMenuItem2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenuItem2ItemStateChanged(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Ayuda");

        jMenuItem1.setText("Acerca de");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void limpiar(DefaultTableModel modelo)
     {
        while(modelo.getRowCount()>0){
        modelo.removeRow(0);
     }
     }
   
 

 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ChartPanel panel;
        String[] resultados= new String[6];
        XYSeriesCollection dataset= new XYSeriesCollection();
        XYSeries serie1= new XYSeries("Entrenamiento");
        XYSeries serie2= new XYSeries("Validacion");
        grafico.removeAll();
        //acierto hay 2 posiciones, la primera 2 para los datos del entenamiento y las 2 restantes para la validacion
        tablaResultadoEntrenamiento=(DefaultTableModel)this.resultadosEntrenamientos.getModel();
        tablaEntrenamiento = (DefaultTableModel) this.tabla.getModel();
        this.limpiar(tablaEntrenamiento);
        unModelo.entrenarRed(Double.parseDouble(factor.getText()), Double.parseDouble(momento.getText()),Integer.parseInt(iteracion.getText()), Integer.parseInt(cantidadNeuronasOcultas.getText()));
        this.entrenamiento = (List)unModelo.getEntrenamiento();
        this.aciertos= unModelo.getAciertos();
        this.erroresEntrenamiento= unModelo.getErroresEntrenamiento();
        this.erroresValidacion= unModelo.getErroresValidacion();
        
        this.error= unModelo.getError();
        for(int i=0;i<entrenamiento.size();i++)
        {
            tablaEntrenamiento.addRow((String[])entrenamiento.get(i));
        }
        serie1= cargarSerie(erroresEntrenamiento, "Entrenamiento");
        serie2= cargarSerie(erroresValidacion, "Validacion");
        dataset.addSeries(serie1);
        dataset.addSeries(serie2);
        JFreeChart chart = ChartFactory.createXYLineChart("Entrenamiento de la RNA",
        "Iteracion","Error",dataset,PlotOrientation.VERTICAL,
        true,
        true,
        false                // Show legend
        );
        panel= new ChartPanel(chart);
        panel.setBounds(2,2, 507, 287);
        grafico.add(panel);
        grafico.repaint();
       //copiar los resultados a la variable resultados
       resultados[0]= "Entrenamiento";
       //error generado por el grupo de entrenamiento 
       resultados[1]=String.valueOf(df.format(error[0]/(datosEntrenamientoProcesados.size())));
       resultados[2]=(String.valueOf(aciertos[0]));
       resultados[3]=(String.valueOf((datosEntrenamientoProcesados.size())-aciertos[0]));
       resultados[4]= (String.valueOf(df.format((aciertos[0] *100)/datosEntrenamientoProcesados.size())));
       resultados[5]= (String.valueOf(df.format(100-(aciertos[0] *100)/datosEntrenamientoProcesados.size())));
       
       tablaResultadoEntrenamiento.addRow(resultados);
 
       //copiar los resultados a la variable resultados
       resultados[0]= "Validacion";
       //error generado por el grupo de entrenamiento 
       resultados[1]=String.valueOf(df.format(error[1]/datosValidacionProcesados.size()));
       resultados[2]=(String.valueOf(aciertos[1]));
       resultados[3]=(String.valueOf(datosValidacionProcesados.size()-(aciertos[1])));
       resultados[4]= String.valueOf(df.format((aciertos[1]*100)/datosValidacionProcesados.size()));
       resultados[5]= (String.valueOf(df.format(100-(aciertos[1]*100)/datosValidacionProcesados.size())));
 
       tablaResultadoEntrenamiento.addRow(resultados);
}//GEN-LAST:event_jButton1ActionPerformed
   
    private XYSeries cargarSerie(List lista, String nombre)
    {
        XYSeries auxiliarSeries= new XYSeries(nombre.toString());
        for (int i=0; i<lista.size();i++)
            auxiliarSeries.add(i,(Float)lista.get(i));
        return auxiliarSeries;
    }
    
    private void factorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factorActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_factorActionPerformed

    public class FormatoTablaUsuarios extends DefaultTableCellRenderer
    {
    public Component getTableCellRendererComponent (JTable table, Object value, boolean selected, boolean focused, int row, int column)
    {
         // SI EN CADA FILA DE LA TABLA LA CELDA 5 ES IGUAL A ACTIVO COLOR AZUL
    if(String.valueOf(table.getValueAt(row,5)).equals("ACTIVO"))  setForeground(Color.blue);
                  // SI NO ES ACTIVO ENTONCES COLOR ROJO
    else  
        setForeground(Color.YELLOW);
    super.getTableCellRendererComponent(table, value, selected, focused, row, column);
    return this;
    }
    }
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       //variable para guardar todos los datos
        
        unModelo.cargarDatos(bd1.getText(), bd2.getText(), bd3.getText());
        this.datosEntrenamientoProcesados= (List)unModelo.getDatosEntrenamiento();
        this.datosValidacionProcesados= (List)unModelo.getDatosValidacion();
        
        modelo = (DefaultTableModel) this.basedatos.getModel();
        basedatos.setBackground(Color.BLACK);
        basedatos.setForeground(Color.GREEN);
        this.limpiar(modelo);
        String[] auxiliar;
        for (int i=0; i <datosEntrenamientoProcesados.size();i++)
        {
            auxiliar= (String[])datosEntrenamientoProcesados.get(i);
            modelo.addRow(auxiliar);
        }
        for (int i=0; i <datosValidacionProcesados.size();i++)
        {
            auxiliar= (String[])datosValidacionProcesados.get(i);
            modelo.addRow(auxiliar);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

       
  
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String ruta= seleccionarArchivo().toString();
            if (!ruta.equals(""))
            ruta1.setText(ruta.toString());
    }//GEN-LAST:event_jButton3ActionPerformed
    private String seleccionarArchivo()
    {
        File archivo=null;
        String valorArchivo="";
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Base de datos", "xls");
        fileChooser.setFileFilter(filter);
        fileChooser.setDialogTitle("Abrir archivo...");
        File ruta = new File("D:/Dropbox/Archivos del análisis/alumnos clasificados por su rendimiento/clasificacion 60 20 20");
        fileChooser.setCurrentDirectory(ruta);
        int result = fileChooser.showOpenDialog(null);
        if(result==JFileChooser.APPROVE_OPTION)
            {
                archivo= fileChooser.getSelectedFile();
                valorArchivo= archivo.toString();
            }
        return valorArchivo;
}
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
             String ruta= seleccionarArchivo().toString();
            if (!ruta.equals(""))
            bd1.setText(ruta.toString()); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          double[] variablesIncluidas= new double[3];
          resultado.setDefaultRenderer(Object.class, new formatoTabla());
          String datosTest[]= new String[5];
          DefaultTableModel testeo = (DefaultTableModel) this.resultado.getModel();
          DefaultTableModel resultadoTesteo= (DefaultTableModel)this.resultadosValidacion.getModel();
          this.limpiar(testeo); 
          double errorTesteo=0;
          Integer aciertosTesteo=0;
          List listaTesteo= new ArrayList();
          //cargo las variable incluidas
          for (int i=0;i<3 ; i++)
              variablesIncluidas[i]=0;
          if (checkPrimerCuatrimestre.isSelected())
          variablesIncluidas[0]=1;
          if (checkSegundoCuatrimestre.isSelected())
              variablesIncluidas[1]=1;
          if (checkVariablesCensales.isSelected())
              variablesIncluidas[2]=1;
          
          unModelo.testeo(ruta1.getText(), ruta2.getText(), variablesIncluidas); 
          errorTesteo= unModelo.getErrorTesteo();
          aciertosTesteo= unModelo.getAciertoTesteo();
          listaTesteo= unModelo.getTesteo();
//        
        for(int i=0;i <listaTesteo.size();i++)
        testeo.addRow((String[])listaTesteo.get(i));
        datosTest[0]= String.valueOf(df.format(errorTesteo/listaTesteo.size()));
        datosTest[1]= String.valueOf(aciertosTesteo);
        datosTest[2]=String.valueOf(listaTesteo.size()-(aciertosTesteo));
        datosTest[3]= String.valueOf(df.format((aciertosTesteo*100)/listaTesteo.size()));      
        datosTest[4]=(String.valueOf(df.format(100-(aciertosTesteo*100)/listaTesteo.size())));
        resultadoTesteo.addRow(datosTest);
//         TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed
    
        private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

            String ruta= seleccionarArchivo().toString();
            if (!ruta.equals(""))
            bd3.setText(ruta.toString());
            // TODO add your handling code here:
        }//GEN-LAST:event_jButton6ActionPerformed

        private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         String ruta= seleccionarArchivo().toString();
            if (!ruta.equals(""))
            ruta2.setText(ruta.toString());
            // TODO add your handling code here:
        }//GEN-LAST:event_jButton7ActionPerformed

        private void saActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saActionPerformed
            String ruta= seleccionarArchivo().toString();
            if (!ruta.equals(""))
            bd2.setText(ruta.toString()); 
            // TODO add your handling code here:
        }//GEN-LAST:event_saActionPerformed

        private void jMenuItem2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenuItem2ItemStateChanged
            // TODO add your handling code here:
        }//GEN-LAST:event_jMenuItem2ItemStateChanged

        private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
            opcionesConfiguracion ventana= new opcionesConfiguracion(unModelo);
            ventana.show();
            // TODO add your handling code here:
        }//GEN-LAST:event_jMenuItem2ActionPerformed

        private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_jMenu2ActionPerformed

        private void ruta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruta1ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_ruta1ActionPerformed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable basedatos;
    private javax.swing.JTextField bd1;
    private javax.swing.JTextField bd2;
    private javax.swing.JTextField bd3;
    private javax.swing.JTextField cantidadNeuronasOcultas;
    private javax.swing.JCheckBox checkPrimerCuatrimestre;
    private javax.swing.JCheckBox checkSegundoCuatrimestre;
    private javax.swing.JCheckBox checkVariablesCensales;
    private javax.swing.JLabel errorgenerado;
    private javax.swing.JTextField factor;
    private javax.swing.JPanel grafico;
    private javax.swing.JTextField iteracion;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField momento;
    private javax.swing.JTable resultado;
    private javax.swing.JTable resultadosEntrenamientos;
    private javax.swing.JTable resultadosValidacion;
    private javax.swing.JTextField ruta1;
    private javax.swing.JTextField ruta2;
    private javax.swing.JButton sa;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
